version: "3.8"

services:
  backend:
    image: pgauin/shadow-backend:latest
    container_name: shadow-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - shadow-network

  frontend:
    image: pgauin/shadow-frontend:latest
    container_name: shadow-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443" # Open the SSL port
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt # Where certs will live
      - ./certbot/www:/var/www/certbot # Where the challenge happens
    networks:
      - shadow-network

  certbot:
    image: certbot/certbot
    container_name: shadow-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - shadow-network

networks:
  shadow-network:
    driver: bridge
