version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: shadow-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shadow-network

  backend:
    image: pgauin/shadow-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shadow-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - shadow-network

  frontend:
    image: pgauin/shadow-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # I put your actual IP here:
        - VITE_API_BASE_URL=http://34.135.8.240:8000
    container_name: shadow-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shadow-network

mongo-express:
  image: mongo-express
  container_name: shadow-mongo-express
  restart: always
  ports:
    - "8081:8081"
  environment:
    # Connects to the 'mongo' service defined above
    ME_CONFIG_MONGODB_SERVER: mongo
    # Login for the Web Interface (You type this in the browser)
    ME_CONFIG_BASICAUTH_USERNAME: admin
    ME_CONFIG_BASICAUTH_PASSWORD: pass
  networks:
    - shadow-network

# --- THIS WAS MISSING BEFORE ---
volumes:
  mongo_data:

networks:
  shadow-network:
    driver: bridge
